user:
  outputs:
    default:
      account: DYYLALF-PM34378
      auth_type: password
      client_session_keep_alive: false
      connect_retries: 3
      connect_timeout: 30
      database: GOTLAND_RAIN
      password: hesvew-goMje3-vykcot
      retry_on_database_errors: true
      role: null
      schema: ANALYTICS
      threads: 6
      type: snowflake
      user: hida7
      warehouse: COMPUTE_WH
  target: default
