# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'gotland_rain_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'gotland_rain_dbt'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
#
# Here we define how models in different folders should be materialized.
# staging/ models become views
# marts/ models become tables

models:
  gotland_rain_dbt:

    staging:
      +materialized: view

    marts:
      +materialized: table